# Workflow
# Should have name
name: Hello

# on tells when the workflow should run (Give indentation by tab)
on:
  workflow_dispatch: 
# Jobs
# Should be inside the workflow

# Job tells what the workflow should do, there can be one or more jobs hence we write jobs
jobs:
  # 1st Job (give indentation)
  say-hello:
    # Creates an Ephermal container with ubuntu running
    runs-on: ubuntu-latest
    # That Ephermal container will have steps to execute, hence name those steps and use run: run has the command
    steps:
      - name: Say Hello to everyone
        run: echo "Hello Doston"

# Steps
# Should be inside the job

# Actions
# Should be inside the Steps
